[template]
src = "confd_stream.conf.tmpl"
dest = "/etc/gomqtt/stream.toml"
keys = [
        "/gomqtt/stream/version",
        "/gomqtt/stream/isdebug",
        "/gomqtt/stream/loglevel",
        "/gomqtt/stream/logpath",
]
reload_cmd = "/Users/scc/Documents/gowork/src/github.com/aiyun/gomqtt/stream/stream reload"
