[common]
version = "0.1.0"
is_debug = true
log_level = "info"
log_path = "./out.log"

[etcd]
#addrs = ["127.0.0.1:2379"]
addrs = ["10.7.24.191:2379",  "10.7.24.192:2379"]
dltimeout = 10
rqtimeout = 10
report_time = 5
report_dir = "/gomqtt/stream/etcd/reportdir"
ttl = 15

[grpc]
addr = ""
port = "8389"

[nats]
addrs = ["nats://10.7.14.236:4222","nats://10.7.14.26:4222"]