site_name: Gomqtt
docs_dir: docs
theme_dir: docs/themes/yeti   

site_favicon: favicon.png

extra_css:
    - css/emccode-font.css
    - css/hX.css

site_favicon: favicon.png

markdown_extensions:
    - admonition

pages:
- 主页: index.md

- 技术解密:
   - 架构设计: tech/architecture.md
   - 协议解析: tech/proto.md

- 用户文档:
   - 安装: user-guide/install.md
   - 配置: user-guide/configuration.md
 
- About:
   - Contributing: about/contribute.md
   - Licence: about/licence.md
   - Release Notes: about/release-notes.md
