[template]
src = "confd_gateway.conf.tmpl"
dest = "/etc/gomqtt/gateway.toml"
keys = [
        "/gomqtt/gateway/version",
        "/gomqtt/gateway/isdebug",
        "/gomqtt/gateway/loglevel",
        "/gomqtt/gateway/logpath",
        "/gomqtt/gateway/invoked",
        "/gomqtt/gateway/tcpaddr",
        "/gomqtt/gateway/enabletls",
        "/gomqtt/gateway/tlscert",
        "/gomqtt/gateway/tlskey",
	"/gomqtt/gateway/etcdaddrs",
	"/gomqtt/gateway/etcdkey",
        "/gomqtt/gateway/qosmax",
        "/gomqtt/gateway/maxkeepalive",
]
reload_cmd = "/Users/sunfei/Documents/GoLibs/src/github.com/aiyun/gomqtt/gateway/gateway reload"
